INSERT INTO alert_state (id, last_seen_total) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------------
-- LEAGUES
-- ---------------------------------------------------------------------------
-- Generated by scripts/seed/generate-tables.py --table leagues, transcribed from a seeded
-- database, not hand-typed. `legacy_name` carries the exact legacy `name` token -- 'UCL'/'EPL'
-- for the two leagues the app has always inserted under an abbreviation, name_en for the other
-- eight -- because the clubs roster INSERT further below still joins ON l.name = c.league_name
-- using those tokens. Writing name_en into `name` here would match nothing on a fresh database
-- and insert zero clubs.
CREATE TEMP TABLE seed_leagues (seed_key TEXT PRIMARY KEY, legacy_name TEXT, name_en TEXT, name_he TEXT, name_ru TEXT, logo_url TEXT, sort_order INTEGER, has_divisions BOOLEAN) ON COMMIT DROP;
INSERT INTO seed_leagues VALUES
    ('israeli-premier-league', 'Israeli Premier League', 'Israeli Premier League', 'ליגת העל', 'Израильская Премьер-лига', 'https://upload.wikimedia.org/wikipedia/en/1/17/Winnerleague.png', 0, FALSE),
    ('liga-leumit', 'Liga Leumit', 'Liga Leumit', 'ליגה לאומית', 'Лига Леумит', 'https://upload.wikimedia.org/wikipedia/en/1/17/Winnerleague.png', 1, FALSE),
    ('premier-league', 'EPL', 'Premier League', 'הפרמייר ליג', 'Премьер-лига', 'https://b.fssta.com/uploads/application/soccer/competition-logos/EnglishPremierLeague.png', 2, FALSE),
    ('la-liga', 'La Liga', 'La Liga', 'לה ליגה', 'Ла Лига', 'https://assets.laliga.com/assets/logos/LL_RGB_h_color/LL_RGB_h_color.png', 3, FALSE),
    ('bundesliga', 'Bundesliga', 'Bundesliga', 'הבונדסליגה', 'Бундеслига', '/logos/bundesliga.svg', 4, FALSE),
    ('serie-a', 'Serie A', 'Serie A', 'סרייה A', 'Серия А', '/logos/serie-a.svg', 5, FALSE),
    ('uefa-champions-league', 'UCL', 'UEFA Champions League', 'ליגת האלופות', 'Лига чемпионов', '/logos/uefa-champions-league.svg', 6, FALSE),
    ('uefa-europa-league', 'UEFA Europa League', 'UEFA Europa League', 'הליגה האירופית', 'Лига Европы', '/logos/uefa-europa-league.svg', 7, FALSE),
    ('world-cup-2026', 'World Cup 2026', 'World Cup 2026', 'מונדיאל 2026', 'Чемпионат мира 2026', 'https://upload.wikimedia.org/wikipedia/commons/1/17/2026_FIFA_World_Cup_emblem.svg', 8, FALSE),
    ('nations-league', 'Nations League', 'Nations League', 'ליגת האומות', 'Лига наций УЕФА', '/logos/uefa-nations-league.svg', 9, TRUE);

-- Adopt rows that predate seed_key, keyed on name_en. Not on the legacy `name` column: the
-- admin endpoints overwrite it with name_he on any save, and 3 of 10 production leagues already
-- carry a drifted one.
UPDATE leagues t SET seed_key = s.seed_key
FROM seed_leagues s
WHERE t.seed_key IS NULL AND t.name_en = s.name_en;

-- Refuse to insert a duplicate of a row that exists but could not be adopted. This is the
-- 2026-07-17 incident: a phantom 'UCL' row produced duplicate clubs and crashed init_db on
-- every pod boot. Failing loudly here is the better failure -- and the neutrality harness is
-- what stops it reaching production at all.
DO $$
DECLARE unadopted TEXT;
BEGIN
    SELECT string_agg(s.seed_key, ', ') INTO unadopted
    FROM seed_leagues s
    WHERE NOT EXISTS (SELECT 1 FROM leagues t WHERE t.seed_key = s.seed_key)
      AND EXISTS (SELECT 1 FROM leagues t
                  WHERE t.name_en = s.name_en OR t.name_he = s.name_he);
    IF unadopted IS NOT NULL THEN
        RAISE EXCEPTION 'seed.sql: leagues % exist but were not adopted; a name matches '
                        'while seed_key does not. Fix the adoption matcher -- inserting '
                        'would duplicate the row (2026-07-17 incident).', unadopted;
    END IF;
END $$;

-- `name` gets the LEGACY token, not name_en: the clubs roster below still joins
-- ON l.name = c.league_name using 'UCL'/'EPL'. Writing name_en here matches nothing on a
-- fresh database and inserts zero clubs. The UPDATE below deliberately never touches `name`,
-- so an adopted row keeps whatever production holds (Hebrew, on 3 of 10 rows).
INSERT INTO leagues (seed_key, name, name_en, name_he, name_ru, logo_url, sort_order, has_divisions)
SELECT s.seed_key, s.legacy_name, s.name_en, s.name_he, s.name_ru, s.logo_url,
       s.sort_order, s.has_divisions
FROM seed_leagues s
WHERE NOT EXISTS (SELECT 1 FROM leagues t WHERE t.seed_key = s.seed_key);

-- Admin-ownable columns yield to admin_edited; seed-owned ones are written unconditionally.
UPDATE leagues t SET
    name_en       = CASE WHEN 'name_en'  = ANY(t.admin_edited) THEN t.name_en  ELSE s.name_en  END,
    name_he       = CASE WHEN 'name_he'  = ANY(t.admin_edited) THEN t.name_he  ELSE s.name_he  END,
    name_ru       = CASE WHEN 'name_ru'  = ANY(t.admin_edited) THEN t.name_ru  ELSE s.name_ru  END,
    logo_url      = CASE WHEN 'logo_url' = ANY(t.admin_edited) THEN t.logo_url ELSE s.logo_url END,
    sort_order    = s.sort_order,
    has_divisions = s.has_divisions
FROM seed_leagues s
WHERE t.seed_key = s.seed_key;

-- ---------------------------------------------------------------------------
-- CLUBS
-- ---------------------------------------------------------------------------
-- Generated by scripts/seed/generate-tables.py --table clubs, transcribed from a seeded database,
-- not hand-typed -- 212 rows is exactly the kind of retyping that produces a silently wrong row.
-- Unlike leagues, clubs need no `legacy_name` column: the old roster INSERT wrote the English name
-- straight into the legacy `name` column (`SELECT l.id, c.name` where c.name is e.g. 'Real Madrid'),
-- identical to name_en, so writing name_en into `name` here for a newly-inserted club matches the
-- old behaviour exactly.
--
-- `league` and `also_in` resolve against leagues.seed_key (Task 4's temp table) -- a club playing
-- two competitions (e.g. Bayern Munich: uefa-champions-league + bundesliga) carries both, because
-- _VOTE_LEAGUES_TOUCHED_CTE in services/worker/rollups.py derives league scope from BOTH league_id
-- and domestic_league_id; losing either would silently under-count a multi-league ballot.
CREATE TEMP TABLE seed_clubs (seed_key TEXT PRIMARY KEY, league TEXT, also_in TEXT, name_en TEXT, name_he TEXT, name_ru TEXT, logo_url TEXT, group_label TEXT) ON COMMIT DROP;
INSERT INTO seed_clubs VALUES
    ('beitar-jerusalem', 'israeli-premier-league', NULL, 'Beitar Jerusalem', 'בית"ר ירושלים', 'Бейтар Иерусалим', 'https://upload.wikimedia.org/wikipedia/en/6/61/Beitar_Jerusalem.png', NULL),
    ('bnei-sakhnin', 'israeli-premier-league', NULL, 'Bnei Sakhnin', 'בני סכנין', 'Бней Сахнин', 'https://upload.wikimedia.org/wikipedia/he/b/bb/Hapo%C3%83%C2%ABl_Bnei_Sakhnin.png', NULL),
    ('hapoel-be-er-sheva', 'israeli-premier-league', NULL, 'Hapoel Be''er Sheva', 'הפועל באר שבע', 'Хапоэль Беэр-Шева', 'https://upload.wikimedia.org/wikipedia/en/8/85/Logo-hapoel-positive.svg', NULL),
    ('hapoel-haifa', 'israeli-premier-league', NULL, 'Hapoel Haifa', 'הפועל חיפה', 'Хапоэль Хайфа', 'https://upload.wikimedia.org/wikipedia/en/e/e4/Hapoel_Haifa_New_Logo.png', NULL),
    ('hapoel-jerusalem', 'israeli-premier-league', NULL, 'Hapoel Jerusalem', 'הפועל ירושלים', 'Хапоэль Иерусалим', 'https://upload.wikimedia.org/wikipedia/en/5/5d/FC_Hapoel_Jerusalem_2021.png', NULL),
    ('hapoel-petah-tikva', 'israeli-premier-league', NULL, 'Hapoel Petah Tikva', 'הפועל פתח תקווה', 'Хапоэль Петах-Тиква', 'https://upload.wikimedia.org/wikipedia/he/6/63/Hapoel_Petach_Tikva_logo.png', NULL),
    ('hapoel-ramat-gan-givatayim', 'israeli-premier-league', NULL, 'Hapoel Ramat Gan Givatayim', 'הפועל רמת-גן גבעתיים', 'Хапоэль Рамат-Ган Гиватаим', 'https://upload.wikimedia.org/wikipedia/en/9/91/Hapoel_ramat-gan.svg', NULL),
    ('hapoel-tel-aviv', 'israeli-premier-league', NULL, 'Hapoel Tel Aviv', 'הפועל תל אביב', 'Хапоэль Тель-Авив', 'https://upload.wikimedia.org/wikipedia/en/a/ac/Hapoel_Tel_Aviv_F.C.png', NULL),
    ('ironi-kiryat-shmona', 'israeli-premier-league', NULL, 'Ironi Kiryat Shmona', 'עירוני קריית שמונה', 'Ирони Кирьят-Шмона', 'https://upload.wikimedia.org/wikipedia/en/d/d1/Hapoel_Ironi_Kiryat_Shmona_badge.png', NULL),
    ('ironi-tiberias', 'israeli-premier-league', NULL, 'Ironi Tiberias', 'עירוני טבריה', 'Ирони Тверия', 'https://upload.wikimedia.org/wikipedia/he/8/84/Ironi_logo_new.gif', NULL),
    ('maccabi-haifa', 'israeli-premier-league', NULL, 'Maccabi Haifa', 'מכבי חיפה', 'Маккаби Хайфа', 'https://upload.wikimedia.org/wikipedia/he/1/1e/%D7%A1%D7%9E%D7%9C_%D7%9E%D7%9B%D7%91%D7%99_%D7%97%D7%99%D7%A4%D7%94_2023.png', NULL),
    ('maccabi-netanya', 'israeli-premier-league', NULL, 'Maccabi Netanya', 'מכבי נתניה', 'Маккаби Нетания', 'https://upload.wikimedia.org/wikipedia/he/b/bc/MaccabiNetanyaNewlogo2021.png', NULL),
    ('maccabi-petah-tikva', 'israeli-premier-league', NULL, 'Maccabi Petah Tikva', 'מכבי פתח תקווה', 'Маккаби Петах-Тиква', 'https://upload.wikimedia.org/wikipedia/he/9/93/MPT_FC_2024.png', NULL),
    ('maccabi-tel-aviv', 'israeli-premier-league', NULL, 'Maccabi Tel Aviv', 'מכבי תל אביב', 'Маккаби Тель-Авив', 'https://upload.wikimedia.org/wikipedia/he/4/45/Maccabi_Tel_Aviv_FC.png', NULL),
    ('bnei-yehuda', 'liga-leumit', NULL, 'Bnei Yehuda', 'בני יהודה', 'Бней Иегуда', 'https://upload.wikimedia.org/wikipedia/en/f/f5/Bnei_Jehuda_Tel_Aviv_FC.svg', NULL),
    ('f-c-ashdod', 'liga-leumit', NULL, 'F.C. Ashdod', 'מ.ס. אשדוד', 'Ашдод', 'https://upload.wikimedia.org/wikipedia/he/5/5b/Ashdod.png', NULL),
    ('f-c-kafr-qasim', 'liga-leumit', NULL, 'F.C. Kafr Qasim', 'מ.ס. כפר קאסם', 'ФК Кафр-Касем', 'https://upload.wikimedia.org/wikipedia/he/6/6f/FC_Kafr_Qasim_Logo.png', NULL),
    ('f-c-kiryat-yam', 'liga-leumit', NULL, 'F.C. Kiryat Yam', 'מ.ס. קריית ים', 'ФК Кирьят-Ям', '/logos/kiryat-yam.png', NULL),
    ('hapoel-afula', 'liga-leumit', NULL, 'Hapoel Afula', 'הפועל עפולה', 'Хапоэль Афула', 'https://upload.wikimedia.org/wikipedia/en/0/01/Hapoel_Afula_F.C.png', NULL),
    ('hapoel-akko', 'liga-leumit', NULL, 'Hapoel Akko', 'הפועל עכו', 'Хапоэль Акко', 'https://upload.wikimedia.org/wikipedia/he/7/75/Hapoelakko.png', NULL),
    ('hapoel-kfar-saba', 'liga-leumit', NULL, 'Hapoel Kfar Saba', 'הפועל כפר סבא', 'Хапоэль Кфар-Сава', 'https://upload.wikimedia.org/wikipedia/he/8/87/Hapoel_Kfar_Saba_FC_Logo.png', NULL),
    ('hapoel-kfar-shalem', 'liga-leumit', NULL, 'Hapoel Kfar Shalem', 'הפועל כפר שלם', 'Хапоэль Кфар-Шалем', 'https://upload.wikimedia.org/wikipedia/he/9/90/Hapoel_Kfar_Shalem_Logo.png', NULL),
    ('hapoel-ra-anana', 'liga-leumit', NULL, 'Hapoel Ra''anana', 'הפועל רעננה', 'Хапоэль Раанана', 'https://upload.wikimedia.org/wikipedia/en/3/3f/HapoelRaanana.png', NULL),
    ('hapoel-rishon-lezion', 'liga-leumit', NULL, 'Hapoel Rishon LeZion', 'הפועל ראשון לציון', 'Хапоэль Ришон-ле-Цион', 'https://upload.wikimedia.org/wikipedia/he/c/ce/Hap-rish.png', NULL),
    ('ironi-modi-in', 'liga-leumit', NULL, 'Ironi Modi''in', 'עירוני מודיעין', 'Ирони Модиин', 'https://upload.wikimedia.org/wikipedia/he/d/d6/IroniModiinFC.png', NULL),
    ('maccabi-akhi-nazareth', 'liga-leumit', NULL, 'Maccabi Akhi Nazareth', 'מכבי אחי נצרת', 'Маккаби Ахей Нацрат', 'https://upload.wikimedia.org/wikipedia/he/3/37/Akhi_Nazareth_FC_Maalouf.png', NULL),
    ('maccabi-bnei-reineh', 'liga-leumit', NULL, 'Maccabi Bnei Reineh', 'מכבי בני ריינה', 'Маккаби Бней Рейне', 'https://upload.wikimedia.org/wikipedia/he/f/f7/MaccabiBneiReine2022.png', NULL),
    ('maccabi-herzliya', 'liga-leumit', NULL, 'Maccabi Herzliya', 'מכבי הרצליה', 'Маккаби Герцлия', 'https://upload.wikimedia.org/wikipedia/he/f/f5/Maccabi_Herzliya.png', NULL),
    ('maccabi-kavilio-jaffa', 'liga-leumit', NULL, 'Maccabi Kavilio Jaffa', 'מכבי קביליו יפו', 'Маккаби Кавильо Яффо', 'https://upload.wikimedia.org/wikipedia/he/8/88/MaccabiJaffaCrestNew2018.png', NULL),
    ('maccabi-kiryat-gat', 'liga-leumit', NULL, 'Maccabi Kiryat Gat', 'מכבי קריית גת', 'Маккаби Кирьят-Гат', '/logos/kiryat-gat.png', NULL),
    ('aston-villa', 'premier-league', 'uefa-champions-league', 'Aston Villa', 'אסטון וילה', 'Астон Вилла', 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg', NULL),
    ('bournemouth', 'premier-league', 'uefa-europa-league', 'Bournemouth', 'בורנמות''', 'Борнмут', 'https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg', NULL),
    ('brentford', 'premier-league', NULL, 'Brentford', 'ברנטפורד', 'Брентфорд', 'https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg', NULL),
    ('brighton-hove-albion', 'premier-league', NULL, 'Brighton & Hove Albion', 'ברייטון אנד הוב אלביון', 'Брайтон энд Хоув Альбион', 'https://upload.wikimedia.org/wikipedia/en/d/d0/Brighton_and_Hove_Albion_FC_crest.svg', NULL),
    ('chelsea', 'premier-league', NULL, 'Chelsea', 'צ''לסי', 'Челси', 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg', NULL),
    ('coventry-city', 'premier-league', NULL, 'Coventry City', 'קובנטרי סיטי', 'Ковентри Сити', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Coventry_City_FC_crest.svg', NULL),
    ('crystal-palace', 'premier-league', 'uefa-europa-league', 'Crystal Palace', 'קריסטל פאלאס', 'Кристал Пэлас', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg', NULL),
    ('everton', 'premier-league', NULL, 'Everton', 'אברטון', 'Эвертон', 'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg', NULL),
    ('fulham', 'premier-league', NULL, 'Fulham', 'פולהאם', 'Фулхэм', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg', NULL),
    ('hull-city', 'premier-league', NULL, 'Hull City', 'האל סיטי', 'Халл Сити', 'https://upload.wikimedia.org/wikipedia/en/5/54/Hull_City_A.F.C._logo.svg', NULL),
    ('ipswich-town', 'premier-league', NULL, 'Ipswich Town', 'איפסוויץ'' טאון', 'Ипсвич Таун', 'https://upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg', NULL),
    ('leeds-united', 'premier-league', NULL, 'Leeds United', 'לידס יונייטד', 'Лидс Юнайтед', 'https://upload.wikimedia.org/wikipedia/en/5/54/Leeds_United_F.C._logo.svg', NULL),
    ('newcastle-united', 'premier-league', NULL, 'Newcastle United', 'ניוקאסל יונייטד', 'Ньюкасл Юнайтед', 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg', NULL),
    ('nottingham-forest', 'premier-league', NULL, 'Nottingham Forest', 'נוטינגהאם פורסט', 'Ноттингем Форест', 'https://upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg', NULL),
    ('sunderland', 'premier-league', 'uefa-europa-league', 'Sunderland', 'סנדרלנד', 'Сандерленд', 'https://upload.wikimedia.org/wikipedia/en/7/77/Logo_Sunderland.svg', NULL),
    ('tottenham-hotspur', 'premier-league', NULL, 'Tottenham Hotspur', 'טוטנהאם הוטספר', 'Тоттенхэм Хотспур', 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg', NULL),
    ('alaves', 'la-liga', NULL, 'Alavés', 'אלאבס', 'Алавес', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Deportivo_Alaves_logo_%282020%29.svg', NULL),
    ('athletic-bilbao', 'la-liga', NULL, 'Athletic Bilbao', 'אתלטיק בילבאו', 'Атлетик Бильбао', 'https://upload.wikimedia.org/wikipedia/en/9/98/Club_Athletic_Bilbao_logo.svg', NULL),
    ('celta-vigo', 'la-liga', 'uefa-europa-league', 'Celta Vigo', 'סלטה ויגו', 'Сельта', 'https://upload.wikimedia.org/wikipedia/en/1/12/RC_Celta_de_Vigo_logo.svg', NULL),
    ('deportivo-de-a-coruna', 'la-liga', NULL, 'Deportivo de A Coruña', 'דפורטיבו דה א-קורוניה', 'Депортиво Ла-Корунья', 'https://upload.wikimedia.org/wikipedia/en/5/56/RC_Deportivo_A_Coru%C3%B1a_logo_2026.svg', NULL),
    ('elche', 'la-liga', NULL, 'Elche', 'אלצ''ה', 'Эльче', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Elche_CF_logo.svg', NULL),
    ('espanyol', 'la-liga', NULL, 'Espanyol', 'אספניול', 'Эспаньол', 'https://upload.wikimedia.org/wikipedia/en/9/92/RCD_Espanyol_crest.svg', NULL),
    ('getafe', 'la-liga', NULL, 'Getafe', 'חטאפה', 'Хетафе', 'https://upload.wikimedia.org/wikipedia/en/4/46/Getafe_logo.svg', NULL),
    ('levante', 'la-liga', NULL, 'Levante', 'לבאנטה', 'Леванте', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Levante_Uni%C3%B3n_Deportiva%2C_S.A.D._logo.svg', NULL),
    ('malaga', 'la-liga', NULL, 'Málaga', 'מאלגה', 'Малага', 'https://upload.wikimedia.org/wikipedia/en/6/6d/M%C3%A1laga_CF.svg', NULL),
    ('osasuna', 'la-liga', NULL, 'Osasuna', 'אוססונה', 'Осасуна', 'https://upload.wikimedia.org/wikipedia/en/3/38/CA_Osasuna_2024_crest.svg', NULL),
    ('racing-santander', 'la-liga', NULL, 'Racing Santander', 'ראסינג סנטנדר', 'Расинг Сантандер', 'https://upload.wikimedia.org/wikipedia/en/f/f5/Racing_de_Santander_logo.svg', NULL),
    ('rayo-vallecano', 'la-liga', NULL, 'Rayo Vallecano', 'ראיו ואייקאנו', 'Райо Вальекано', 'https://upload.wikimedia.org/wikipedia/en/d/d8/Rayo_Vallecano_logo.svg', NULL),
    ('real-betis', 'la-liga', 'uefa-champions-league', 'Real Betis', 'ריאל בטיס', 'Реал Бетис', 'https://upload.wikimedia.org/wikipedia/en/2/2f/Real_Betis_2022_logo.svg', NULL),
    ('real-sociedad', 'la-liga', 'uefa-europa-league', 'Real Sociedad', 'ריאל סוסיאדד', 'Реал Сосьедад', 'https://upload.wikimedia.org/wikipedia/en/f/f1/Real_Sociedad_logo.svg', NULL),
    ('sevilla', 'la-liga', NULL, 'Sevilla', 'סביליה', 'Севилья', 'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg', NULL),
    ('valencia', 'la-liga', NULL, 'Valencia', 'ולנסיה', 'Валенсия', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Valenciacf.svg', NULL),
    ('villarreal', 'la-liga', 'uefa-champions-league', 'Villarreal', 'ויאריאל', 'Вильярреал', 'https://upload.wikimedia.org/wikipedia/en/b/b9/Villarreal_CF_logo-en.svg', NULL),
    ('1-fc-koln', 'bundesliga', NULL, '1. FC Köln', 'פ. צ. קלן', 'Кёльн', 'https://upload.wikimedia.org/wikipedia/commons/0/01/1._FC_Koeln_Logo_2014%E2%80%93.svg', NULL),
    ('bayer-leverkusen', 'bundesliga', 'uefa-europa-league', 'Bayer Leverkusen', 'באייר לברקוזן', 'Байер 04', 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg', NULL),
    ('borussia-monchengladbach', 'bundesliga', NULL, 'Borussia Mönchengladbach', 'בורוסיה מנשנגלדבך', 'Боруссия Мёнхенгладбах', 'https://upload.wikimedia.org/wikipedia/commons/8/81/Borussia_M%C3%B6nchengladbach_logo.svg', NULL),
    ('eintracht-frankfurt', 'bundesliga', NULL, 'Eintracht Frankfurt', 'איינטרכט פרנקפורט', 'Айнтрахт Франкфурт', 'https://upload.wikimedia.org/wikipedia/en/7/7e/Eintracht_Frankfurt_crest.svg', NULL),
    ('fc-augsburg', 'bundesliga', NULL, 'FC Augsburg', 'אוגסבורג', 'Аугсбург', 'https://upload.wikimedia.org/wikipedia/en/c/c5/FC_Augsburg_logo.svg', NULL),
    ('fc-schalke-04', 'bundesliga', NULL, 'FC Schalke 04', 'שאלקה 04', 'Шальке 04', 'https://upload.wikimedia.org/wikipedia/commons/6/6d/FC_Schalke_04_Logo.svg', NULL),
    ('hamburger-sv', 'bundesliga', NULL, 'Hamburger SV', 'המבורג', 'Гамбург', 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Hamburger_SV_logo.svg', NULL),
    ('mainz-05', 'bundesliga', NULL, 'Mainz 05', 'מיינץ 05', 'Майнц 05', 'https://upload.wikimedia.org/wikipedia/commons/1/1b/1._FSV_Mainz_05_logo.svg', NULL),
    ('rb-leipzig', 'bundesliga', 'uefa-champions-league', 'RB Leipzig', 'ר. ב. לייפציג', 'РБ Лейпциг', 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg', NULL),
    ('sc-freiburg', 'bundesliga', NULL, 'SC Freiburg', 'פרייבורג', 'Фрайбург', 'https://upload.wikimedia.org/wikipedia/en/6/6d/SC_Freiburg_logo.svg', NULL),
    ('sc-paderborn-07', 'bundesliga', NULL, 'SC Paderborn 07', 'פאדרבורן 07', 'Падерборн 07', 'https://upload.wikimedia.org/wikipedia/commons/6/67/SC_Paderborn_07_Logo_new.svg', NULL),
    ('sv-elversberg', 'bundesliga', NULL, 'SV Elversberg', 'אלוורסברג', 'Эльферсберг', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/SV_Elversberg_Logo_2021.svg', NULL),
    ('tsg-hoffenheim', 'bundesliga', 'uefa-europa-league', 'TSG Hoffenheim', 'הופנהיים', 'Хоффенхайм', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Logo_TSG_Hoffenheim.svg', NULL),
    ('union-berlin', 'bundesliga', NULL, 'Union Berlin', 'אוניון ברלין', 'Унион Берлин', 'https://upload.wikimedia.org/wikipedia/commons/4/44/1._FC_Union_Berlin_Logo.svg', NULL),
    ('vfb-stuttgart', 'bundesliga', 'uefa-champions-league', 'VfB Stuttgart', 'שטוטגרט', 'Штутгарт', 'https://upload.wikimedia.org/wikipedia/commons/e/eb/VfB_Stuttgart_1893_Logo.svg', NULL),
    ('werder-bremen', 'bundesliga', NULL, 'Werder Bremen', 'וורדר ברמן', 'Вердер', 'https://upload.wikimedia.org/wikipedia/commons/b/be/SV-Werder-Bremen-Logo.svg', NULL),
    ('ac-milan', 'serie-a', 'uefa-europa-league', 'AC Milan', 'מילאן', 'Милан', 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg', NULL),
    ('atalanta', 'serie-a', NULL, 'Atalanta', 'אטלנטה', 'Аталанта', 'https://upload.wikimedia.org/wikipedia/en/f/f2/Atalanta_BC_new_logo.svg', NULL),
    ('bologna', 'serie-a', NULL, 'Bologna', 'בולוניה', 'Болонья', 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Bologna_F.C._1909_logo.svg', NULL),
    ('cagliari', 'serie-a', NULL, 'Cagliari', 'קליארי', 'Кальяри', 'https://upload.wikimedia.org/wikipedia/en/6/61/Cagliari_Calcio_1920.svg', NULL),
    ('como', 'serie-a', 'uefa-champions-league', 'Como', 'קומו', 'Комо', 'https://upload.wikimedia.org/wikipedia/commons/9/99/Calcio_Como_-_logo_%28Italy%2C_2019-%29.svg', NULL),
    ('fiorentina', 'serie-a', NULL, 'Fiorentina', 'פיורנטינה', 'Фиорентина', 'https://upload.wikimedia.org/wikipedia/commons/8/8c/ACF_Fiorentina_-_logo_%28Italy%2C_2022%29.svg', NULL),
    ('frosinone', 'serie-a', NULL, 'Frosinone', 'פרוזינונה', 'Фрозиноне', 'https://upload.wikimedia.org/wikipedia/en/0/0b/Frosinone_Calcio_logo.svg', NULL),
    ('genoa', 'serie-a', NULL, 'Genoa', 'ג''נואה', 'Дженоа', 'https://upload.wikimedia.org/wikipedia/en/2/2c/Genoa_CFC_crest.svg', NULL),
    ('juventus', 'serie-a', 'uefa-europa-league', 'Juventus', 'יובנטוס', 'Ювентус', 'https://upload.wikimedia.org/wikipedia/commons/e/ed/Juventus_FC_-_logo_black_%28Italy%2C_2020%29.svg', NULL),
    ('lazio', 'serie-a', NULL, 'Lazio', 'לאציו', 'Лацио', 'https://upload.wikimedia.org/wikipedia/en/c/ce/S.S._Lazio_badge.svg', NULL),
    ('lecce', 'serie-a', NULL, 'Lecce', 'לצ''ה', 'Лечче', 'https://upload.wikimedia.org/wikipedia/en/2/23/US_Lecce_crest.svg', NULL),
    ('monza', 'serie-a', NULL, 'Monza', 'מונצה', 'Монца', 'https://upload.wikimedia.org/wikipedia/en/a/a7/AC_Monza_logo_%282021%29.svg', NULL),
    ('parma', 'serie-a', NULL, 'Parma', 'פארמה', 'Парма', 'https://upload.wikimedia.org/wikipedia/commons/9/97/Logo_Parma_Calcio_1913_%28adozione_2016%29.svg', NULL),
    ('roma', 'serie-a', 'uefa-champions-league', 'Roma', 'רומא', 'Рома', 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg', NULL),
    ('sassuolo', 'serie-a', NULL, 'Sassuolo', 'ססואולו', 'Сассуоло', 'https://upload.wikimedia.org/wikipedia/en/1/1c/US_Sassuolo_Calcio_logo.svg', NULL),
    ('torino', 'serie-a', NULL, 'Torino', 'טורינו', 'Торино', 'https://upload.wikimedia.org/wikipedia/en/2/2e/Torino_FC_Logo.svg', NULL),
    ('udinese', 'serie-a', NULL, 'Udinese', 'אודינזה', 'Удинезе', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Udinese_Calcio_logo.svg', NULL),
    ('venezia', 'serie-a', NULL, 'Venezia', 'ונציה', 'Венеция', 'https://upload.wikimedia.org/wikipedia/en/3/39/Venezia_FC_crest.svg', NULL),
    ('arsenal', 'uefa-champions-league', 'premier-league', 'Arsenal', 'ארסנל', 'Арсенал', 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', NULL),
    ('atletico-madrid', 'uefa-champions-league', 'la-liga', 'Atlético Madrid', 'אתלטיקו מדריד', 'Атлетико Мадрид', 'https://upload.wikimedia.org/wikipedia/en/f/f9/Atletico_Madrid_Logo_2024.svg', NULL),
    ('barcelona', 'uefa-champions-league', 'la-liga', 'Barcelona', 'ברצלונה', 'Барселона', 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', NULL),
    ('bayern-munich', 'uefa-champions-league', 'bundesliga', 'Bayern Munich', 'באיירן מינכן', 'Бавария', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/FC_Bayern_M%C3%BCnchen_logo_%282024%29.svg', NULL),
    ('borussia-dortmund', 'uefa-champions-league', 'bundesliga', 'Borussia Dortmund', 'בורוסיה דורטמונד', 'Боруссия Дортмунд', 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg', NULL),
    ('club-brugge', 'uefa-champions-league', NULL, 'Club Brugge', 'קלאב ברוז''', 'Брюгге', 'https://upload.wikimedia.org/wikipedia/commons/9/97/Club_brugge.png', NULL),
    ('feyenoord', 'uefa-champions-league', NULL, 'Feyenoord', 'פיינורד', 'Фейеноорд', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Feyenoord_logo_since_2024.svg', NULL),
    ('galatasaray', 'uefa-champions-league', NULL, 'Galatasaray', 'גלאטסראיי', 'Галатасарай', 'https://upload.wikimedia.org/wikipedia/commons/0/07/Galatasaray_S.K._Logo_2026_5-stars.svg', NULL),
    ('inter-milan', 'uefa-champions-league', 'serie-a', 'Inter Milan', 'אינטר מילאנו', 'Интернационале', 'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg', NULL),
    ('lens', 'uefa-champions-league', NULL, 'Lens', 'לאנס', 'Ланс', 'https://upload.wikimedia.org/wikipedia/en/c/cc/RC_Lens_logo.svg', NULL),
    ('lille', 'uefa-champions-league', NULL, 'Lille', 'ליל', 'Лилль', 'https://upload.wikimedia.org/wikipedia/en/3/3f/Lille_OSC_2018_logo.svg', NULL),
    ('liverpool', 'uefa-champions-league', 'premier-league', 'Liverpool', 'ליברפול', 'Ливерпуль', 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', NULL),
    ('manchester-city', 'uefa-champions-league', 'premier-league', 'Manchester City', 'מנצ''סטר סיטי', 'Манчестер Сити', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg', NULL),
    ('manchester-united', 'uefa-champions-league', 'premier-league', 'Manchester United', 'מנצ''סטר יונייטד', 'Манчестер Юнайтед', 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', NULL),
    ('napoli', 'uefa-champions-league', 'serie-a', 'Napoli', 'נאפולי', 'Наполи', 'https://upload.wikimedia.org/wikipedia/commons/4/4d/SSC_Napoli_2025_%28white_and_azure%29.svg', NULL),
    ('paris-saint-germain', 'uefa-champions-league', NULL, 'Paris Saint-Germain', 'פריז סן ז''רמן', 'Пари Сен-Жермен', 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg', NULL),
    ('porto', 'uefa-champions-league', NULL, 'Porto', 'פורטו', 'Порту', 'https://upload.wikimedia.org/wikipedia/en/f/f1/FC_Porto.svg', NULL),
    ('psv-eindhoven', 'uefa-champions-league', NULL, 'PSV Eindhoven', 'פ.ס.וו. איינדהובן', 'ПСВ', 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven.svg', NULL),
    ('real-madrid', 'uefa-champions-league', 'la-liga', 'Real Madrid', 'ריאל מדריד', 'Реал Мадрид', 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', NULL),
    ('shakhtar-donetsk', 'uefa-champions-league', NULL, 'Shakhtar Donetsk', 'שחטאר דונצק', 'Шахтёр Донецк', 'https://upload.wikimedia.org/wikipedia/en/a/a1/FC_Shakhtar_Donetsk.svg', NULL),
    ('slavia-prague', 'uefa-champions-league', NULL, 'Slavia Prague', 'סלביה פראג', 'Славия Прага', 'https://upload.wikimedia.org/wikipedia/commons/2/2b/SK_Slavia_Praha_full_logo.svg', NULL),
    ('sporting-cp', 'uefa-champions-league', NULL, 'Sporting CP', 'ספורטינג ליסבון', 'Спортинг Лиссабон', 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Sporting_Clube_de_Portugal_2026.svg', NULL),
    ('olympiacos', 'uefa-europa-league', NULL, 'Olympiacos', 'אולימפיאקוס', 'Олимпиакос', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Olympiacos_FC_crest.svg', NULL),
    ('olympique-de-marseille', 'uefa-europa-league', NULL, 'Olympique de Marseille', 'אולימפיק מרסיי', 'Олимпик Марсель', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Olympique_de_Marseille_2026_logo.svg', NULL),
    ('sparta-prague', 'uefa-europa-league', NULL, 'Sparta Prague', 'ספרטה פראג', 'Спарта Прага', 'https://upload.wikimedia.org/wikipedia/commons/d/dd/AC-Sparta-LOGO2021.svg', NULL),
    ('stade-rennais', 'uefa-europa-league', NULL, 'Stade Rennais', 'סטאד רן', 'Ренн', 'https://upload.wikimedia.org/wikipedia/en/9/9e/Stade_Rennais_FC.svg', NULL),
    ('sturm-graz', 'uefa-europa-league', NULL, 'Sturm Graz', 'שטורם גראץ', 'Штурм', 'https://upload.wikimedia.org/wikipedia/en/9/91/SK_Sturm_Graz_logo.svg', NULL),
    ('torreense', 'uefa-europa-league', NULL, 'Torreense', 'טורנסה', 'Униан Торренсе', 'https://upload.wikimedia.org/wikipedia/en/d/dc/S.C.U._Torreense_logo.svg', NULL),
    ('union-saint-gilloise', 'uefa-europa-league', NULL, 'Union Saint-Gilloise', 'אוניון סן-ז''ילואז', 'Юнион Сент-Жиллуаз', 'https://upload.wikimedia.org/wikipedia/en/1/11/Royale_Union_Saint-Gilloise_logo.svg', NULL),
    ('algeria', 'world-cup-2026', NULL, 'Algeria', 'אלג''יריה', 'Алжир', 'https://upload.wikimedia.org/wikipedia/en/2/2d/Algerian_NT_%28logo%29.png', NULL),
    ('argentina', 'world-cup-2026', NULL, 'Argentina', 'ארגנטינה', 'Аргентина', 'https://upload.wikimedia.org/wikipedia/en/c/c1/Argentina_national_football_team_logo.svg', NULL),
    ('australia', 'world-cup-2026', NULL, 'Australia', 'אוסטרליה', 'Австралия', 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Australia_national_football_team_badge.svg', NULL),
    ('austria', 'world-cup-2026', 'nations-league', 'Austria', 'אוסטריה', 'Австрия', 'https://upload.wikimedia.org/wikipedia/en/b/b7/Austria_national_football_team_crest.svg', 'B'),
    ('belgium', 'world-cup-2026', 'nations-league', 'Belgium', 'בלגיה', 'Бельгия', 'https://upload.wikimedia.org/wikipedia/en/f/f9/Royal_Belgian_FA_logo_2019.svg', 'A'),
    ('bosnia-and-herzegovina', 'world-cup-2026', 'nations-league', 'Bosnia and Herzegovina', 'בוסניה והרצגובינה', 'Босния и Герцеговина', 'https://upload.wikimedia.org/wikipedia/en/d/da/Football_Association_of_Bosnia_and_Herzegovina_logo.svg', 'B'),
    ('brazil', 'world-cup-2026', NULL, 'Brazil', 'ברזיל', 'Бразилия', 'https://upload.wikimedia.org/wikipedia/commons/3/32/Confedera%C3%A7%C3%A3o_Brasileira_de_Futebol_logo_%282020%29.svg', NULL),
    ('canada', 'world-cup-2026', NULL, 'Canada', 'קנדה', 'Канада', 'https://upload.wikimedia.org/wikipedia/commons/6/69/Canadian_Soccer_Association_logo.svg', NULL),
    ('cape-verde', 'world-cup-2026', NULL, 'Cape Verde', 'קייפ ורדה', 'Кабо-Верде', 'https://upload.wikimedia.org/wikipedia/en/c/ce/Cape_Verdean_Football_Federation_logo.svg', NULL),
    ('colombia', 'world-cup-2026', NULL, 'Colombia', 'קולומביה', 'Колумбия', 'https://upload.wikimedia.org/wikipedia/commons/2/29/FCF-Logo-2023.svg', NULL),
    ('croatia', 'world-cup-2026', 'nations-league', 'Croatia', 'קרואטיה', 'Хорватия', 'https://upload.wikimedia.org/wikipedia/en/e/ea/Croatia_national_football_team_logo.svg', 'A'),
    ('curacao', 'world-cup-2026', NULL, 'Curaçao', 'קוראסאו', 'Кюрасао', 'https://upload.wikimedia.org/wikipedia/en/1/1c/Curacao_Football_Federation.svg', NULL),
    ('czech-republic', 'world-cup-2026', 'nations-league', 'Czech Republic', 'צ''כיה', 'Чехия', 'https://upload.wikimedia.org/wikipedia/en/7/76/Czech_Republic_national_football_team_logo.svg', 'A'),
    ('dr-congo', 'world-cup-2026', NULL, 'DR Congo', 'קונגו הדמוקרטית', 'ДР Конго', 'https://upload.wikimedia.org/wikipedia/en/6/62/Congolese_Association_Football_Federation_logo.png', NULL),
    ('ecuador', 'world-cup-2026', NULL, 'Ecuador', 'אקוודור', 'Эквадор', 'https://upload.wikimedia.org/wikipedia/commons/e/e3/Logo_de_la_Federaci%C3%B3n_Ecuatoriana_de_F%C3%BAtbol_%282%29.svg', NULL),
    ('egypt', 'world-cup-2026', NULL, 'Egypt', 'מצרים', 'Египет', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Egyptian_Football_Association_logo.svg', NULL),
    ('england', 'world-cup-2026', 'nations-league', 'England', 'אנגליה', 'Англия', 'https://upload.wikimedia.org/wikipedia/en/8/8b/England_national_football_team_crest.svg', 'A'),
    ('france', 'world-cup-2026', 'nations-league', 'France', 'צרפת', 'Франция', 'https://upload.wikimedia.org/wikipedia/en/1/12/France_national_football_team_seal.svg', 'A'),
    ('germany', 'world-cup-2026', 'nations-league', 'Germany', 'גרמניה', 'Германия', 'https://upload.wikimedia.org/wikipedia/en/e/e3/DFBEagle.svg', 'A'),
    ('ghana', 'world-cup-2026', NULL, 'Ghana', 'גאנה', 'Гана', 'https://upload.wikimedia.org/wikipedia/en/9/9c/Ghana_Football_Association_logo_%282001%29.svg', NULL),
    ('haiti', 'world-cup-2026', NULL, 'Haiti', 'האיטי', 'Гаити', 'https://upload.wikimedia.org/wikipedia/en/e/e7/Federation_Haitienne_de_Football.png', NULL),
    ('iran', 'world-cup-2026', NULL, 'Iran', 'איראן', 'Иран', 'https://upload.wikimedia.org/wikipedia/en/d/d6/Football_Federation_Islamic_Republic_of_Iran_logo.svg', NULL),
    ('iraq', 'world-cup-2026', NULL, 'Iraq', 'עיראק', 'Ирак', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Iraq_National_Team_Badge_2021_v1.svg', NULL),
    ('ivory-coast', 'world-cup-2026', NULL, 'Ivory Coast', 'חוף השנהב', 'Кот-д''Ивуар', 'https://upload.wikimedia.org/wikipedia/en/0/09/Ivory_Coast_national_football_team_logo.svg', NULL),
    ('japan', 'world-cup-2026', NULL, 'Japan', 'יפן', 'Япония', 'https://upload.wikimedia.org/wikipedia/en/8/84/Japan_national_football_team_crest.svg', NULL),
    ('jordan', 'world-cup-2026', NULL, 'Jordan', 'ירדן', 'Иордания', 'https://upload.wikimedia.org/wikipedia/commons/5/54/Jordan_national_football_team_logo_2024.svg', NULL),
    ('mexico', 'world-cup-2026', NULL, 'Mexico', 'מקסיקו', 'Мексика', 'https://upload.wikimedia.org/wikipedia/en/3/3f/Mexico_national_football_team_crest.svg', NULL),
    ('morocco', 'world-cup-2026', NULL, 'Morocco', 'מרוקו', 'Марокко', 'https://upload.wikimedia.org/wikipedia/en/d/d0/Royal_Moroccan_Football_Federation_logo.svg', NULL),
    ('netherlands', 'world-cup-2026', 'nations-league', 'Netherlands', 'הולנד', 'Нидерланды', 'https://upload.wikimedia.org/wikipedia/en/7/78/Netherlands_national_football_team_logo.svg', 'A'),
    ('new-zealand', 'world-cup-2026', NULL, 'New Zealand', 'ניו זילנד', 'Новая Зеландия', 'https://upload.wikimedia.org/wikipedia/en/3/3a/New_Zealand_Football_Crest_2022.svg', NULL),
    ('norway', 'world-cup-2026', 'nations-league', 'Norway', 'נורווגיה', 'Норвегия', 'https://upload.wikimedia.org/wikipedia/en/6/6c/Norway_national_football_team_logo.svg', 'A'),
    ('panama', 'world-cup-2026', NULL, 'Panama', 'פנמה', 'Панама', 'https://upload.wikimedia.org/wikipedia/en/e/ee/Panamanian_Football_Federation_logo_2024.svg', NULL),
    ('paraguay', 'world-cup-2026', NULL, 'Paraguay', 'פרגוואי', 'Парагвай', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol_logo.svg', NULL),
    ('portugal', 'world-cup-2026', 'nations-league', 'Portugal', 'פורטוגל', 'Португалия', 'https://upload.wikimedia.org/wikipedia/en/e/e4/Portugal_national_football_team_logo.svg', 'A'),
    ('qatar', 'world-cup-2026', NULL, 'Qatar', 'קטאר', 'Катар', 'https://upload.wikimedia.org/wikipedia/en/3/3a/Qatar_Football_Association_logo.svg', NULL),
    ('saudi-arabia', 'world-cup-2026', NULL, 'Saudi Arabia', 'ערב הסעודית', 'Саудовская Аравия', 'https://upload.wikimedia.org/wikipedia/en/e/ee/Saudi_Arabia_national_football_team_logo.svg', NULL),
    ('scotland', 'world-cup-2026', 'nations-league', 'Scotland', 'סקוטלנד', 'Шотландия', 'https://upload.wikimedia.org/wikipedia/en/5/50/Scotland_national_football_team_logo_2014.svg', 'B'),
    ('senegal', 'world-cup-2026', NULL, 'Senegal', 'סנגל', 'Сенегал', 'https://upload.wikimedia.org/wikipedia/en/1/16/Senegalese_Football_Federation_logo.svg', NULL),
    ('south-africa', 'world-cup-2026', NULL, 'South Africa', 'דרום אפריקה', 'ЮАР', 'https://upload.wikimedia.org/wikipedia/en/e/e7/South_Africa_national_soccer_team_logo.svg', NULL),
    ('south-korea', 'world-cup-2026', NULL, 'South Korea', 'דרום קוריאה', 'Южная Корея', 'https://upload.wikimedia.org/wikipedia/en/4/41/South_Korea_national_football_team.svg', NULL),
    ('spain', 'world-cup-2026', 'nations-league', 'Spain', 'ספרד', 'Испания', 'https://upload.wikimedia.org/wikipedia/en/3/39/Spain_national_football_team_crest.svg', 'A'),
    ('sweden', 'world-cup-2026', 'nations-league', 'Sweden', 'שוודיה', 'Швеция', 'https://upload.wikimedia.org/wikipedia/en/3/3f/Sweden_national_football_team_badge.svg', 'B'),
    ('switzerland', 'world-cup-2026', 'nations-league', 'Switzerland', 'שווייץ', 'Швейцария', 'https://upload.wikimedia.org/wikipedia/en/a/a0/Swiss_Football_Association_logo.svg', 'B'),
    ('tunisia', 'world-cup-2026', NULL, 'Tunisia', 'תוניסיה', 'Тунис', 'https://upload.wikimedia.org/wikipedia/en/c/c4/Tunisia_national_football_team_logo.png', NULL),
    ('turkey', 'world-cup-2026', 'nations-league', 'Turkey', 'טורקיה', 'Турция', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Roundel_flag_of_Turkey.svg', 'A'),
    ('uruguay', 'world-cup-2026', NULL, 'Uruguay', 'אורוגוואי', 'Уругвай', 'https://upload.wikimedia.org/wikipedia/en/4/43/Uruguay_national_football_team_seal.svg', NULL),
    ('usa', 'world-cup-2026', NULL, 'USA', 'ארה"ב', 'США', 'https://upload.wikimedia.org/wikipedia/commons/1/1e/United_States_Soccer_Federation_logo.svg', NULL),
    ('uzbekistan', 'world-cup-2026', NULL, 'Uzbekistan', 'אוזבקיסטן', 'Узбекистан', 'https://upload.wikimedia.org/wikipedia/en/3/3d/Uzbekistan_Football_Association.svg', NULL),
    ('albania', 'nations-league', NULL, 'Albania', 'אלבניה', 'Албания', 'https://upload.wikimedia.org/wikipedia/commons/3/30/Stema_e_Fanell%C3%ABs_s%C3%AB_Komb%C3%ABtares.svg', 'C'),
    ('andorra', 'nations-league', NULL, 'Andorra', 'אנדורה', 'Андорра', 'https://upload.wikimedia.org/wikipedia/commons/4/4e/Coat_of_arms_of_Andorra.svg', 'D'),
    ('armenia', 'nations-league', NULL, 'Armenia', 'ארמניה', 'Армения', 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Coat_of_arms_of_Armenia.svg', 'C'),
    ('azerbaijan', 'nations-league', NULL, 'Azerbaijan', 'אזרבייג''ן', 'Азербайджан', 'https://upload.wikimedia.org/wikipedia/en/5/5e/AFFA_logo.png', 'D'),
    ('belarus', 'nations-league', NULL, 'Belarus', 'בלארוס', 'Беларусь', 'https://upload.wikimedia.org/wikipedia/commons/4/48/Coat_of_arms_of_Belarus_(2020%E2%80%93present).svg', 'C'),
    ('bulgaria', 'nations-league', NULL, 'Bulgaria', 'בולגריה', 'Болгария', 'https://upload.wikimedia.org/wikipedia/en/1/11/Bgnatcrest.png', 'C'),
    ('cyprus', 'nations-league', NULL, 'Cyprus', 'קפריסין', 'Кипр', 'https://upload.wikimedia.org/wikipedia/en/6/6b/Cyprus_national_football_team_logo.png', 'C'),
    ('denmark', 'nations-league', NULL, 'Denmark', 'דנמרק', 'Дания', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Dansk_boldspil_union_logo.svg', 'A'),
    ('estonia', 'nations-league', NULL, 'Estonia', 'אסטוניה', 'Эстония', 'https://upload.wikimedia.org/wikipedia/en/a/a2/Estonian_Football_Association_logo.svg', 'C'),
    ('faroe-islands', 'nations-league', NULL, 'Faroe Islands', 'איי פארו', 'Фарерские острова', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Faroe_Islands_Football_Association_logo.svg', 'C'),
    ('finland', 'nations-league', NULL, 'Finland', 'פינלנד', 'Финляндия', 'https://upload.wikimedia.org/wikipedia/commons/8/80/Finland_national_football_team_crest.png', 'C'),
    ('georgia', 'nations-league', NULL, 'Georgia', 'גאורגיה', 'Грузия', 'https://upload.wikimedia.org/wikipedia/en/9/9c/Georgia_national_football_team_crest.svg', 'B'),
    ('gibraltar', 'nations-league', NULL, 'Gibraltar', 'גיברלטר', 'Гибралтар', 'https://upload.wikimedia.org/wikipedia/en/f/fe/Gibraltar_Football_Association_(2020).svg', 'D'),
    ('greece', 'nations-league', NULL, 'Greece', 'יוון', 'Греция', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Greece_National_Football_Team.svg', 'A'),
    ('hungary', 'nations-league', NULL, 'Hungary', 'הונגריה', 'Венгрия', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Coat_of_arms_of_Hungary.svg', 'B'),
    ('iceland', 'nations-league', NULL, 'Iceland', 'איסלנד', 'Исландия', 'https://upload.wikimedia.org/wikipedia/en/6/6d/Iceland_national_football_team_logo.svg', 'C'),
    ('israel', 'nations-league', NULL, 'Israel', 'ישראל', 'Израиль', 'https://upload.wikimedia.org/wikipedia/en/5/5a/Israel_Football_Association_logo.svg', 'B'),
    ('italy', 'nations-league', NULL, 'Italy', 'איטליה', 'Италия', 'https://upload.wikimedia.org/wikipedia/commons/b/bf/Logo_Italy_National_Football_Team_-_2023.svg', 'A'),
    ('kazakhstan', 'nations-league', NULL, 'Kazakhstan', 'קזחסטן', 'Казахстан', 'https://upload.wikimedia.org/wikipedia/en/0/08/Kazakhstan_Football_Federation_logo.svg', 'C'),
    ('kosovo', 'nations-league', NULL, 'Kosovo', 'קוסובו', 'Косово', 'https://upload.wikimedia.org/wikipedia/commons/8/85/Kosovo_National_Football_Team.svg', 'B'),
    ('latvia', 'nations-league', NULL, 'Latvia', 'לטביה', 'Латвия', 'https://upload.wikimedia.org/wikipedia/en/7/7b/Latvia_national_team_logo.png', 'C'),
    ('liechtenstein', 'nations-league', NULL, 'Liechtenstein', 'ליכטנשטיין', 'Лихтенштейн', 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Crown_of_Liechtenstein.svg', 'D'),
    ('lithuania', 'nations-league', NULL, 'Lithuania', 'ליטא', 'Литва', 'https://upload.wikimedia.org/wikipedia/en/8/89/Badge_of_Lithuania_national_football_teams.png', 'D'),
    ('luxembourg', 'nations-league', NULL, 'Luxembourg', 'לוקסמבורג', 'Люксембург', 'https://upload.wikimedia.org/wikipedia/en/9/9d/Luxembourg_national_football_team_crest.png', 'C'),
    ('malta', 'nations-league', NULL, 'Malta', 'מלטה', 'Мальта', 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Malta_national_football_team_crest.svg', 'D'),
    ('moldova', 'nations-league', NULL, 'Moldova', 'מולדובה', 'Молдова', 'https://upload.wikimedia.org/wikipedia/en/c/c9/Moldova_national_football_team.svg', 'C'),
    ('montenegro', 'nations-league', NULL, 'Montenegro', 'מונטנגרו', 'Черногория', 'https://upload.wikimedia.org/wikipedia/en/7/78/Football_Association_of_Montenegro_logo.svg', 'C'),
    ('northern-ireland', 'nations-league', NULL, 'Northern Ireland', 'צפון אירלנד', 'Северная Ирландия', 'https://upload.wikimedia.org/wikipedia/en/2/25/Irish_Football_Association_logo.svg', 'B'),
    ('north-macedonia', 'nations-league', NULL, 'North Macedonia', 'צפון מקדוניה', 'Северная Македония', 'https://upload.wikimedia.org/wikipedia/commons/3/34/Coat_of_arms_of_the_President_of_North_Macedonia.svg', 'B'),
    ('poland', 'nations-league', NULL, 'Poland', 'פולין', 'Польша', 'https://upload.wikimedia.org/wikipedia/commons/c/c9/Herb_Polski.svg', 'B'),
    ('republic-of-ireland', 'nations-league', NULL, 'Republic of Ireland', 'אירלנד', 'Ирландия', 'https://upload.wikimedia.org/wikipedia/en/f/f8/Republic_of_Ireland_national_football_team_crest.svg', 'B'),
    ('romania', 'nations-league', NULL, 'Romania', 'רומניה', 'Румыния', 'https://upload.wikimedia.org/wikipedia/en/e/ef/Romania_national_football_team_logo.svg', 'B'),
    ('san-marino', 'nations-league', NULL, 'San Marino', 'סן מרינו', 'Сан-Марино', 'https://upload.wikimedia.org/wikipedia/commons/3/30/San-marino-logo.png', 'C'),
    ('serbia', 'nations-league', NULL, 'Serbia', 'סרביה', 'Сербия', 'https://upload.wikimedia.org/wikipedia/en/e/eb/Football_Association_of_Serbia_logo.svg', 'A'),
    ('slovakia', 'nations-league', NULL, 'Slovakia', 'סלובקיה', 'Словакия', 'https://upload.wikimedia.org/wikipedia/en/8/8a/Slovak_Football_Association_logo.svg', 'C'),
    ('slovenia', 'nations-league', NULL, 'Slovenia', 'סלובניה', 'Словения', 'https://upload.wikimedia.org/wikipedia/en/9/99/Slovenia_national_football_team.svg', 'B'),
    ('ukraine', 'nations-league', NULL, 'Ukraine', 'אוקראינה', 'Украина', 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Logo_F%C3%A9d%C3%A9ration_Ukraine_Football_2016.svg', 'B'),
    ('wales', 'nations-league', NULL, 'Wales', 'ויילס', 'Уэльс', 'https://upload.wikimedia.org/wikipedia/en/d/dc/Wales_national_football_team_logo.svg', 'A');

-- Adopt rows that predate seed_key, keyed on name_en -- never the legacy `name` column, which the
-- admin endpoints overwrite with name_he on any save (104 of 212 production clubs already carry a
-- drifted one).
UPDATE clubs t SET seed_key = s.seed_key
FROM seed_clubs s
WHERE t.seed_key IS NULL AND t.name_en = s.name_en;

-- Refuse to insert a duplicate of a row that exists but could not be adopted -- see the leagues
-- section above for why (the 2026-07-17 incident): clubs_name_en_uidx is global, so a stray
-- duplicate crashes init_db on every pod boot.
DO $$
DECLARE unadopted TEXT;
BEGIN
    SELECT string_agg(s.seed_key, ', ') INTO unadopted
    FROM seed_clubs s
    WHERE NOT EXISTS (SELECT 1 FROM clubs t WHERE t.seed_key = s.seed_key)
      AND EXISTS (SELECT 1 FROM clubs t
                  WHERE t.name_en = s.name_en OR t.name_he = s.name_he);
    IF unadopted IS NOT NULL THEN
        RAISE EXCEPTION 'seed.sql: clubs % exist but were not adopted; a name matches '
                        'while seed_key does not. Fix the adoption matcher -- inserting '
                        'would duplicate the row and violate clubs_name_en_uidx.', unadopted;
    END IF;
END $$;

INSERT INTO clubs (seed_key, league_id, domestic_league_id, name, name_en, name_he,
                   name_ru, logo_url, group_label)
SELECT s.seed_key, l.id, d.id, s.name_en, s.name_en, s.name_he, s.name_ru,
       s.logo_url, s.group_label
FROM seed_clubs s
JOIN leagues l ON l.seed_key = s.league
LEFT JOIN leagues d ON d.seed_key = s.also_in
WHERE NOT EXISTS (SELECT 1 FROM clubs t WHERE t.seed_key = s.seed_key);

-- domestic_league_id IS admin-writable (PATCH /api/admin/clubs/<id> and the admin UI's
-- continental-competition buttons both set it), so it yields to admin_edited like the
-- names do. group_label does not: both admin club endpoints omit it by design, precisely
-- so a PATCH cannot null it out.
UPDATE clubs t SET
    league_id          = l.id,
    domestic_league_id = CASE WHEN 'domestic_league_id' = ANY(t.admin_edited)
                              THEN t.domestic_league_id ELSE d.id END,
    name_en     = CASE WHEN 'name_en'  = ANY(t.admin_edited) THEN t.name_en  ELSE s.name_en  END,
    name_he     = CASE WHEN 'name_he'  = ANY(t.admin_edited) THEN t.name_he  ELSE s.name_he  END,
    name_ru     = CASE WHEN 'name_ru'  = ANY(t.admin_edited) THEN t.name_ru  ELSE s.name_ru  END,
    logo_url    = CASE WHEN 'logo_url' = ANY(t.admin_edited) THEN t.logo_url ELSE s.logo_url END,
    group_label = s.group_label
FROM seed_clubs s
JOIN leagues l ON l.seed_key = s.league
LEFT JOIN leagues d ON d.seed_key = s.also_in
WHERE t.seed_key = s.seed_key;

INSERT INTO previous_parties (name) VALUES
    ('הליכוד'), ('יש עתיד'), ('הציונות הדתית'), ('המחנה הממלכתי'),
    ('ישראל ביתנו'), ('ש"ס'), ('יהדות התורה'), ('רע"ם'),
    ('חד"ש-תע"ל'), ('העבודה'), ('מרצ'), ('בל"ד'), ('אחר')
ON CONFLICT (name) DO NOTHING;

-- Rename, not a new row. המילואימניקים merged with חילי טרופר's יסודות ישראל and the joint list runs
-- as בית ציוני - המילואימניקים (launched 2026-08-05). This MUST run before the INSERT below: that
-- INSERT's ON CONFLICT matches on `name`, so on an already-seeded database the new literal would not
-- conflict with the old row -- it would add a SECOND party, leaving every vote already cast stranded
-- on an orphaned row while the ballot showed the empty new one.
--
-- Keyed on `name` rather than name_he because on a fresh database name_he is not backfilled until
-- further down this file. Sets both columns, which is what rename_upcoming_party() does (it writes
-- name = name_he). Idempotent: once renamed it matches nothing. It also deliberately does not fire
-- on a row an admin has already renamed to something else -- their edit wins.
UPDATE upcoming_parties
   SET name = 'בית ציוני - המילואימניקים', name_he = 'בית ציוני - המילואימניקים'
 WHERE name = 'המילואימניקים';

INSERT INTO upcoming_parties (name) VALUES
    ('הליכוד'), ('ישר'), ('ביחד'), ('הדמוקרטים'), ('כחול לבן'),
    ('ישראל ביתנו'), ('הציונות הדתית'), ('עוצמה יהודית'), ('חד"ש-תע"ל'),
    ('בל"ד'), ('רע"ם'), ('ש"ס'), ('יהדות התורה'),
    ('המפלגה הכלכלית'), ('אל הדגל'), ('בית ציוני - המילואימניקים'), ('זהות'), ('נעם')
ON CONFLICT (name) DO NOTHING;

-- Backfill each row's own language from the legacy `name` column.
UPDATE leagues           SET name_en = name WHERE name_en IS NULL;
UPDATE clubs             SET name_en = name WHERE name_en IS NULL;
UPDATE previous_parties  SET name_he = name WHERE name_he IS NULL;
UPDATE upcoming_parties  SET name_he = name WHERE name_he IS NULL;

-- Relegation removals (2026-08-04): Hapoel Hadera and Hapoel Nof HaGalil dropped out of Liga Leumit
-- to the third tier, which this app does not seed, and Maccabi Kiryat Gat / Maccabi Akhi Nazareth
-- took their places in the roster above. Dropping the two from the INSERT's VALUES list is only half
-- the change: every statement in this file runs against a database that is ALREADY seeded, so
-- deleting a literal there reaches a *fresh* database only -- production keeps both clubs forever.
-- Removing a club therefore needs its own explicit statement, and this is the first one in the file.
--
-- The NOT EXISTS guard is what keeps the app bootable, and it is not optional. vote_clubs.club_id
-- references clubs(id) with NO ON DELETE CASCADE (schema.sql), so deleting a club somebody has voted
-- for raises a foreign-key violation *inside init_db* -- which runs on every backend pod boot, so the
-- failure is a CrashLoopBackOff on startup, not one failed request. The guard also encodes the policy
-- the admin API already enforces: DELETE /api/admin/clubs/<id> returns 409 while any vote references
-- the club (see delete_club_route in app.py). A roster tidy-up must never destroy a ballot; if either
-- club ever does pick up votes, it stays and the admin UI's vote-reassignment flow is the way out.
--
-- Keyed on name_en, the stable identity used by every other guarded statement here -- so a club an
-- admin has renamed through the live UI is left alone rather than silently deleted. Idempotent: a
-- no-op once the rows are gone, which is why it can run on every boot forever.
DELETE FROM clubs c
WHERE c.name_en IN ('Hapoel Hadera', 'Hapoel Nof HaGalil')
  AND NOT EXISTS (SELECT 1 FROM vote_clubs vc WHERE vc.club_id = c.id);

-- Previous Knesset party display names.
-- One row per entity, all display languages together. COALESCE is the per-column equivalent of
-- the old "AND name_xx IS NULL" guard: it fills only what is still empty, so a name an admin has
-- renamed through the live UI is never overwritten. Do not drop it.
UPDATE previous_parties p SET
    name_en = COALESCE(p.name_en, v.name_en),
    name_ru = COALESCE(p.name_ru, v.name_ru)
FROM (VALUES
    ('הליכוד', 'Likud', 'Ликуд'),
    ('יש עתיד', 'Yesh Atid', 'Еш Атид'),
    ('הציונות הדתית', 'Religious Zionist Party', 'Ха-Цийонут ха-Датит'),
    ('המחנה הממלכתי', 'National Unity', 'Ха-Махане ха-Мамлахти'),
    ('ישראל ביתנו', 'Yisrael Beiteinu', 'Наш дом Израиль'),
    ('ש"ס', 'Shas', 'ШАС'),
    ('יהדות התורה', 'United Torah Judaism', 'Яхадут ха-Тора'),
    ('רע"ם', 'Ra''am', 'РААМ'),
    ('חד"ש-תע"ל', 'Hadash-Ta''al', 'ХАДАШ-ТААЛ'),
    ('העבודה', 'Labor', 'Авода'),
    ('מרצ', 'Meretz', 'МЕРЕЦ'),
    ('בל"ד', 'Balad', 'БАЛАД'),
    ('אחר', 'Other', 'Другое')
) AS v(name_he, name_en, name_ru)
WHERE p.name_he = v.name_he;

-- Admin-curated party logos, synced from the live RDS instance (added via the admin UI's
-- Logo URL field, not originally seeded) so a fresh install matches current production data.
UPDATE previous_parties t SET logo_url = v.logo_url
FROM (VALUES
    ('הליכוד', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Likud_Logo.svg'),
    ('יש עתיד', 'https://upload.wikimedia.org/wikipedia/he/1/12/%D7%99%D7%A9_%D7%A2%D7%AA%D7%99%D7%93_%D7%9C%D7%95%D7%92%D7%95.svg'),
    ('הציונות הדתית', 'https://upload.wikimedia.org/wikipedia/he/c/c2/%D7%9C%D7%95%D7%92%D7%95_%D7%94%D7%A6%D7%99%D7%95%D7%A0%D7%95%D7%AA_%D7%94%D7%93%D7%AA%D7%99%D7%AA_2022.svg'),
    ('המחנה הממלכתי', 'https://upload.wikimedia.org/wikipedia/he/e/e0/%D7%9C%D7%95%D7%92%D7%95_%D7%94%D7%9E%D7%97%D7%A0%D7%94_%D7%94%D7%9E%D7%9E%D7%9C%D7%9B%D7%AA%D7%99_%D7%90%D7%95%D7%92%D7%95%D7%A1%D7%98_2022.svg'),
    ('ישראל ביתנו', 'https://upload.wikimedia.org/wikipedia/he/a/a4/%D7%9C%D7%95%D7%92%D7%95_%D7%99%D7%A9%D7%A8%D7%90%D7%9C_%D7%91%D7%99%D7%AA%D7%A0%D7%95_2022.svg'),
    ('ש"ס', 'https://upload.wikimedia.org/wikipedia/he/0/05/Shas_logo.svg'),
    ('יהדות התורה', 'https://upload.wikimedia.org/wikipedia/he/9/97/%D7%99%D7%94%D7%93%D7%95%D7%AA_%D7%94%D7%AA%D7%95%D7%A8%D7%94_%D7%9C%D7%95%D7%92%D7%95_2019.svg'),
    ('רע"ם', 'https://upload.wikimedia.org/wikipedia/he/0/08/%D7%94%D7%A8%D7%A9%D7%99%D7%9E%D7%94_%D7%94%D7%A2%D7%A8%D7%91%D7%99%D7%AA_%D7%94%D7%9E%D7%90%D7%95%D7%97%D7%93%D7%AA_%D7%9C%D7%95%D7%92%D7%95_2021.svg'),
    ('חד"ש-תע"ל', 'https://upload.wikimedia.org/wikipedia/he/e/eb/%D7%9C%D7%95%D7%92%D7%95_%D7%97%D7%93%D7%B4%D7%A9_%D7%AA%D7%A2%D7%B4%D7%9C_2022_%28%D7%A2%D7%91%D7%A8%D7%99%D7%AA%29.svg'),
    ('העבודה', 'https://upload.wikimedia.org/wikipedia/commons/f/f8/HaAvoda_Logo.svg'),
    ('מרצ', 'https://upload.wikimedia.org/wikipedia/he/f/ff/%D7%9C%D7%95%D7%92%D7%95_%D7%9E%D7%A8%D7%A6_%D7%99%D7%95%D7%9C%D7%99_2022.svg'),
    ('בל"ד', 'https://upload.wikimedia.org/wikipedia/he/1/19/Balad.svg')
) AS v(name_he, logo_url)
WHERE t.name_he = v.name_he
  AND t.logo_url IS NULL;

-- Party ideology classification. The VALUES below are authoritative; the REASONING for every one
-- of them lives in docs/party-classifications.md. Do not restate reasoning in this file -- if a
-- number here needs justifying, justify it there and leave this table plain.
--
-- These UPDATEs are deliberately UNGUARDED, unlike the name/logo_url statements above. Production
-- is always already seeded, so an `AND bloc IS NULL` guard would make every later edit to this
-- table unreachable in production. Unguarded is safe for these six columns specifically: nothing
-- in the app ever writes them (the admin party endpoints only rename), so re-running seed.sql
-- rewrites identical values. Names and logo_url keep their `IS NULL` guards for the opposite
-- reason -- admins DO edit those live, and an unguarded write would destroy their edits.
--
-- 'אחר' (Other) is absent on purpose: it is a catch-all ballot option, not a party, and every
-- ideology column stays NULL. test_migration.py asserts that.
UPDATE previous_parties p SET
    bloc = v.bloc, economic = v.economic, security = v.security,
    religiosity = v.religiosity, sector = v.sector, tags = v.tags
FROM (VALUES
    ('הליכוד', 'bibi', 1, 2, 2, 'traditional', ARRAY['claims-economically-liberal', 'populist', 'nationalist', 'instrumentally-clerical']::text[]),
    ('יש עתיד', 'opposition', 0, 0, -2, 'secular', ARRAY['liberal-zionist', 'centrist']::text[]),
    ('הציונות הדתית', 'bibi', 0, 3, 3, 'religious_zionist', ARRAY['claims-economically-liberal', 'ultranationalist', 'far-right']::text[]),
    ('המחנה הממלכתי', 'unaligned', 1, NULL, -1, 'secular', ARRAY['centrist', 'avoids-security-topic', 'leans-traditional']::text[]),
    ('ישראל ביתנו', 'opposition', 2, 2, -3, 'secular', ARRAY['anti-clerical', 'revisionist-zionist']::text[]),
    ('ש"ס', 'bibi', -2, 1, 2, 'haredi', ARRAY['ultra-orthodox', 'religious-conservative']::text[]),
    ('יהדות התורה', 'bibi', -2, 1, 2, 'haredi', ARRAY['ultra-orthodox', 'religious-conservative']::text[]),
    ('רע"ם', 'opposition', 0, NULL, NULL, 'arab', ARRAY['islamist', 'conservative', 'focuses-on-arab-israeli-civil-issues']::text[]),
    ('חד"ש-תע"ל', 'opposition', -3, -2, NULL, 'arab', ARRAY['communist', 'arab-nationalist', 'pro-two-state']::text[]),
    ('העבודה', 'opposition', -2, -1, -2, 'secular', ARRAY['social-democrat']::text[]),
    ('מרצ', 'opposition', -2, -1, -2, 'secular', ARRAY['social-democrat']::text[]),
    ('בל"ד', 'opposition', -2, -3, -3, 'arab', ARRAY['palestinian-nationalist', 'non-zionist']::text[])
) AS v(name_he, bloc, economic, security, religiosity, sector, tags)
WHERE p.name_he = v.name_he;

-- Party lineage: continuity between previous and upcoming parties (identity, splits, merges).
-- See design spec Appendix -- Yashar, The Economic Party, El HaDegel, The Reservists, and Blue and
-- White (as an independent brand) have no seeded predecessor; 'אחר' has no successor.
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'הליכוד' AND u.name_he = 'הליכוד'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'יש עתיד' AND u.name_he = 'ביחד'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'הציונות הדתית' AND u.name_he = 'הציונות הדתית'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'הציונות הדתית' AND u.name_he = 'עוצמה יהודית'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'הציונות הדתית' AND u.name_he = 'נעם'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'המחנה הממלכתי' AND u.name_he = 'כחול לבן'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'ישראל ביתנו' AND u.name_he = 'ישראל ביתנו'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'ש"ס' AND u.name_he = 'ש"ס'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'יהדות התורה' AND u.name_he = 'יהדות התורה'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'רע"ם' AND u.name_he = 'רע"ם'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'חד"ש-תע"ל' AND u.name_he = 'חד"ש-תע"ל'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'העבודה' AND u.name_he = 'הדמוקרטים'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'מרצ' AND u.name_he = 'הדמוקרטים'
ON CONFLICT DO NOTHING;
INSERT INTO party_lineage (previous_party_id, upcoming_party_id)
SELECT p.id, u.id FROM previous_parties p, upcoming_parties u
WHERE p.name_he = 'בל"ד' AND u.name_he = 'בל"ד'
ON CONFLICT DO NOTHING;

-- Upcoming election party display names.
-- One row per entity, all display languages together. COALESCE is the per-column equivalent of
-- the old "AND name_xx IS NULL" guard: it fills only what is still empty, so a name an admin has
-- renamed through the live UI is never overwritten. Do not drop it.
UPDATE upcoming_parties p SET
    name_en = COALESCE(p.name_en, v.name_en),
    name_ru = COALESCE(p.name_ru, v.name_ru)
FROM (VALUES
    ('הליכוד', 'Likud', 'Ликуд'),
    ('ישר', 'Yashar', 'Яшар'),
    ('ביחד', 'Together', 'Бейахад'),
    ('הדמוקרטים', 'The Democrats', 'Ха-Демократим'),
    ('כחול לבן', 'Blue and White', 'Кахоль-лаван'),
    ('ישראל ביתנו', 'Yisrael Beiteinu', 'Наш дом Израиль'),
    ('הציונות הדתית', 'Religious Zionist Party', 'Ха-Цийонут ха-Датит'),
    ('עוצמה יהודית', 'Otzma Yehudit', 'Оцма Йехудит'),
    ('חד"ש-תע"ל', 'Hadash-Ta''al', 'ХАДАШ-ТААЛ'),
    ('בל"ד', 'Balad', 'БАЛАД'),
    ('רע"ם', 'Ra''am', 'РААМ'),
    ('ש"ס', 'Shas', 'ШАС'),
    ('יהדות התורה', 'United Torah Judaism', 'Яхадут ха-Тора'),
    ('המפלגה הכלכלית', 'The Economic Party', 'Экономическая партия'),
    ('אל הדגל', 'El HaDegel', 'Эль ха-Дегель'),
    ('בית ציוני - המילואימניקים', 'The Reservists', 'Резервисты'),
    ('זהות', 'Zehut', 'Зеут'),
    ('נעם', 'Noam', 'Ноам')
) AS v(name_he, name_en, name_ru)
WHERE p.name_he = v.name_he;

-- Admin-curated data synced from the live RDS instance via scripts/sync-seed-from-rds.sh.
UPDATE upcoming_parties t SET logo_url = v.logo_url
FROM (VALUES
    ('ביחד', 'https://upload.wikimedia.org/wikipedia/commons/1/14/Together-logo-29April.svg'),
    -- Self-hosted: the list's only artwork is on *.fbcdn.net, whose URLs are signed and expire and
    -- which tracker blockers drop in the browser (the F.C. Kiryat Yam failure). Cropped and its
    -- background removed, but otherwise the party's own blue lockup, shown UNCHANGED in both themes
    -- -- 'The Reservists' is in SKIP_RECOLOR_PARTIES in services/frontend/logos.js, because its Star
    -- of David is a knockout and a recolour cannot lift a hole. That file and
    -- docs/party-classifications.md carry the reasoning.
    ('בית ציוני - המילואימניקים', '/logos/beit-tzioni-miluimnikim.png'),
    ('המפלגה הכלכלית', 'https://upload.wikimedia.org/wikipedia/he/c/c9/%D7%94%D7%9E%D7%A4%D7%9C%D7%92%D7%94_%D7%94%D7%9B%D7%9C%D7%9B%D7%9C%D7%99%D7%AA_%D7%94%D7%97%D7%93%D7%A9%D7%94_%D7%9C%D7%95%D7%92%D7%95.svg'),
    ('יהדות התורה', 'https://upload.wikimedia.org/wikipedia/he/9/97/%D7%99%D7%94%D7%93%D7%95%D7%AA_%D7%94%D7%AA%D7%95%D7%A8%D7%94_%D7%9C%D7%95%D7%92%D7%95_2019.svg'),
    ('ישר', 'https://upload.wikimedia.org/wikipedia/commons/6/61/Yashar_party_logo.png'),
    ('רע"ם', 'https://upload.wikimedia.org/wikipedia/he/0/08/%D7%94%D7%A8%D7%A9%D7%99%D7%9E%D7%94_%D7%94%D7%A2%D7%A8%D7%91%D7%99%D7%AA_%D7%94%D7%9E%D7%90%D7%95%D7%97%D7%93%D7%AA_%D7%9C%D7%95%D7%92%D7%95_2021.svg'),
    ('ש"ס', 'https://upload.wikimedia.org/wikipedia/he/0/05/Shas_logo.svg'),

    -- Admin-curated party logos, synced from the live RDS instance (see previous_parties above).
    ('הליכוד', 'https://upload.wikimedia.org/wikipedia/commons/5/50/Likud_Logo.svg'),
    ('הדמוקרטים', 'https://upload.wikimedia.org/wikipedia/commons/b/b5/The_Democrats_led_by_Yair_Golan.svg'),
    ('כחול לבן', 'https://upload.wikimedia.org/wikipedia/he/a/a6/%D7%9C%D7%95%D7%92%D7%95_%D7%9B%D7%97%D7%95%D7%9C_%D7%9C%D7%91%D7%9F_2021.svg'),
    ('ישראל ביתנו', 'https://upload.wikimedia.org/wikipedia/he/a/a4/%D7%9C%D7%95%D7%92%D7%95_%D7%99%D7%A9%D7%A8%D7%90%D7%9C_%D7%91%D7%99%D7%AA%D7%A0%D7%95_2022.svg'),
    -- 2026 rebrand, UPCOMING TABLE ONLY -- previous_parties keeps the 2022 logo, because that row is
    -- the current Knesset faction. Self-hosted because neither Wikimedia revision works in both
    -- themes: the published PNG has the white background baked in (100% opaque, so it trips
    -- recolorLogoForDark()'s solid-tile guard and renders as a white plate on the dark cards), and
    -- the earlier revision it replaced is a white-ink knockout that is invisible in light mode. This
    -- is that PNG with the outer white flood-filled to transparent, which leaves the #31698C
    -- wordmark below the recolour threshold and the teal בראשות bar (luminance 0.518) just above it.
    ('הציונות הדתית', '/logos/religious-zionism-2026.png'),
    ('עוצמה יהודית', 'https://upload.wikimedia.org/wikipedia/he/9/9f/%D7%A2%D7%95%D7%A6%D7%9E%D7%94_%D7%99%D7%94%D7%95%D7%93%D7%99%D7%AA_%D7%9C%D7%95%D7%92%D7%95_2021.svg'),
    ('חד"ש-תע"ל', 'https://upload.wikimedia.org/wikipedia/he/e/eb/%D7%9C%D7%95%D7%92%D7%95_%D7%97%D7%93%D7%B4%D7%A9_%D7%AA%D7%A2%D7%B4%D7%9C_2022_%28%D7%A2%D7%91%D7%A8%D7%99%D7%AA%29.svg'),
    ('בל"ד', 'https://upload.wikimedia.org/wikipedia/he/1/19/Balad.svg'),
    ('זהות', 'https://upload.wikimedia.org/wikipedia/commons/d/d4/ZehutParty.svg'),
    -- Noam's current campaign banner ("נעם לישראל, בראשות אבי מעוז"). It is an opaque JPEG, not a
    -- transparent SVG, so logos.js skips the dark-mode recolour (>90% opaque pixels = solid tile) --
    -- correct here, since the artwork is already light lettering on a dark navy field.
    ('נעם', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/%D7%A1%D7%9E%D7%9C_%D7%9E%D7%A4%D7%9C%D7%92%D7%AA_%D7%A0%D7%A2%D7%9D_j%2Cul.jpg'),
    -- El HaDegel is a new movement with no Wikimedia logo; this is the square Star-of-David emblem
    -- (transparent, from the party's own Webflow CDN "webclip" app-icon) rather than the old low-res
    -- Google thumbnail, which had a dark navy background baked in and rendered as a dark box on the
    -- logo chip. Non-Wikimedia host, so if it ever 404s the frontend falls back to a generated monogram.
    ('אל הדגל', 'https://cdn.prod.website-files.com/674ed46d57366b6a64400c3c/67501afebb4a91b0d0b7c6b9_el-hadegel-webclip.svg')
) AS v(name_he, logo_url)
WHERE t.name_he = v.name_he
  AND t.logo_url IS NULL;

-- Upcoming-party classification. Independent from previous_parties even where a lineage link
-- exists (design spec Decision 1). Same unguarded rationale as the previous_parties block above.
UPDATE upcoming_parties p SET
    bloc = v.bloc, economic = v.economic, security = v.security,
    religiosity = v.religiosity, sector = v.sector, tags = v.tags,
    families = v.families, family_evidence = v.family_evidence
FROM (VALUES
    ('הליכוד', 'bibi', 1, 2, 2, 'traditional', ARRAY['claims-economically-liberal', 'populist', 'nationalist', 'instrumentally-clerical']::text[], ARRAY['conscription-exemption','judicial-restraint','sectoral-budgeting']::text[], 'record'),
    ('ישר', 'opposition', 1, 1, -2, 'secular', ARRAY['new-party', 'centrist', 'liberal-zionist', 'statist', 'security-hawk', 'no-palestinian-state', 'anti-annexation', 'universal-conscription', 'core-curriculum', 'constitutionalist', 'governance-reform', 'anti-monopoly', 'tax-cutting', 'public-service-reform', 'service-conditioned-citizenship', 'sanctions-on-non-servers', 'reservist-focused', 'agricultural-protectionism']::text[], ARRAY['universal-conscription','constitutional-reform','cost-of-living']::text[], 'platform'),
    ('ביחד', 'opposition', 1, NULL, -2, 'secular', ARRAY['liberal-zionist', 'constitutionalist', 'internally-split-on-conflict', 'anti-clerical', 'universal-conscription', 'pro-competition', 'anti-monopoly', 'free-trade', 'kashrut-liberalization']::text[], ARRAY['universal-conscription','constitutional-reform','cost-of-living']::text[], 'platform'),
    ('הדמוקרטים', 'opposition', -2, -1, -3, 'secular', ARRAY['progressive', 'social-democrat', 'liberal-zionist', 'religious-pluralism', 'jewish-arab-partnership', 'protest-movement-rooted', 'two-state', 'anti-annexation', 'anti-settler-violence', 'universal-conscription', 'core-curriculum', 'civil-marriage', 'anti-indicted-pm', 'regional-normalization', 'lgbt-rights', 'reservist-focused', 'gender-equality']::text[], ARRAY['constitutional-reform','welfare-state','jewish-arab-partnership','universal-conscription']::text[], 'platform'),
    ('כחול לבן', 'unaligned', 0, 2, -2, 'secular', ARRAY['centrist', 'hard-to-classify-bloc', 'statist', 'security-hawk', 'no-palestinian-state', 'pro-settlement', 'unity-government', 'public-service-reform', 'universal-conscription', 'sanctions-on-non-servers', 'arab-civil-service', 'scholar-exemption-retained', 'core-curriculum', 'state-haredi-education', 'reservist-focused']::text[], ARRAY['constitutional-reform','universal-conscription']::text[], 'platform'),
    ('ישראל ביתנו', 'opposition', 2, 2, -3, 'secular', ARRAY['anti-clerical', 'revisionist-zionist', 'civil-marriage', 'universal-conscription', 'free-market', 'governance-reform', 'anti-indicted-pm', 'hardline-on-gaza']::text[], ARRAY['universal-conscription','constitutional-reform','market-liberal']::text[], 'record'),
    ('הציונות הדתית', 'bibi', 0, 3, 3, 'religious_zionist', ARRAY['claims-economically-liberal', 'ultranationalist', 'far-right', 'settler-movement', 'judicial-overhaul', 'sovereignty-annexation', 'opposes-hostage-deals', 'halakhic-state', 'anti-two-state', 'death-penalty-for-terrorists', 'reservist-focused']::text[], ARRAY['judicial-restraint','conscription-split','sectoral-budgeting']::text[], 'record'),
    ('עוצמה יהודית', 'bibi', 0, 3, 3, 'religious_zionist', ARRAY['claims-economically-liberal', 'not-economy-focused', 'kahanist', 'jewish-supremacist', 'far-right', 'gun-rights', 'judicial-overhaul', 'pro-settlement', 'sovereignty-annexation', 'temple-mount-centred', 'death-penalty-for-terrorists']::text[], ARRAY['judicial-restraint','not-economy-focused','conscription-by-incentive']::text[], 'record'),
    ('חד"ש-תע"ל', 'opposition', -3, -2, NULL, 'arab', ARRAY['communist', 'arab-nationalist', 'pro-two-state', 'jewish-arab-partnership', 'civil-rights-focused', 'pro-joint-list', 'negev-bedouin-representation']::text[], ARRAY['arab-representation','jewish-arab-partnership','welfare-state']::text[], 'record'),
    ('בל"ד', 'opposition', -2, -3, -3, 'arab', ARRAY['palestinian-nationalist', 'non-zionist', 'state-of-all-its-citizens', 'secular-democratic-state', 'pro-two-state', 'right-of-return', 'anti-privatization', 'progressive-taxation', 'affirmative-action', 'opposes-arab-conscription', 'program-unchanged-since-2018']::text[], ARRAY['arab-representation','welfare-state']::text[], 'record'),
    ('רע"ם', 'opposition', 0, -2, NULL, 'arab', ARRAY['islamist', 'conservative', 'focuses-on-arab-israeli-civil-issues', 'pro-two-state']::text[], ARRAY['arab-representation']::text[], 'record'),
    ('ש"ס', 'bibi', -2, 1, 2, 'haredi', ARRAY['ultra-orthodox', 'religious-conservative']::text[], ARRAY['conscription-exemption','welfare-state','sectoral-budgeting']::text[], 'record'),
    ('יהדות התורה', 'bibi', -2, 1, 2, 'haredi', ARRAY['ultra-orthodox', 'religious-conservative']::text[], ARRAY['conscription-split','welfare-state','sectoral-budgeting']::text[], 'record'),
    ('המפלגה הכלכלית', 'unaligned', 1, 0, -2, 'secular', ARRAY['populist', 'anti-corruption', 'anti-monopoly', 'tax-cutting', 'free-trade', 'consumer-protection', 'kashrut-liberalization', 'single-issue-economy', 'anti-clerical']::text[], ARRAY['cost-of-living']::text[], 'platform'),
    ('אל הדגל', 'unaligned', 1, 2, -2, 'secular', ARRAY['reservist-focused', 'anti-conscription-exemption', 'universal-conscription', 'service-conditioned-citizenship', 'sanctions-on-non-servers', 'core-curriculum', 'sovereignty-annexation', 'preemptive-security-doctrine', 'territorial-price-doctrine', 'anti-two-state', 'voluntary-emigration-incentives', 'constitutionalist', 'governance-reform', 'term-limits', 'state-commission-of-inquiry', 'pm-immunity-protections', 'municipal-devolution', 'deregulation', 'cost-of-living', 'workforce-integration']::text[], ARRAY['universal-conscription','reservist-movement','constitutional-reform','cost-of-living']::text[], 'platform'),
    ('בית ציוני - המילואימניקים', 'unaligned', 1, 2, -2, 'secular', ARRAY['reservist-focused', 'anti-conscription-exemption', 'universal-conscription', 'service-conditioned-citizenship', 'sanctions-on-non-servers', 'core-curriculum', 'anti-netanyahu', 'territorial-control-gaza', 'anti-two-state', 'pro-settlement', 'anti-monopoly', 'free-trade', 'cost-of-living', 'constitutionalist', 'governance-reform', 'statist', 'excludes-haredi-and-arab-parties']::text[], ARRAY['universal-conscription','reservist-movement','constitutional-reform','cost-of-living']::text[], 'platform'),
    ('זהות', 'bibi', 3, 3, 2, 'religious_zionist', ARRAY['libertarian', 'small-government', 'flat-tax', 'deregulation', 'privatization', 'anti-monopoly', 'cannabis-legalization', 'gun-rights', 'sovereignty-annexation', 'anti-two-state', 'population-transfer', 'permanent-residency-not-citizenship', 'state-institutions-bound-to-halakha', 'ends-state-religious-funding', 'jewish-law-parallel-jurisdiction', 'communitarian-devolution', 'temple-mount-centred', 'professional-army', 'extra-parliamentary']::text[], ARRAY['judicial-restraint','market-liberal','cost-of-living']::text[], 'platform'),
    ('נעם', 'bibi', NULL, 3, 3, 'religious_zionist', ARRAY['hardal', 'religious-fundamentalist', 'single-issue-jewish-identity', 'not-economy-focused', 'halakhic-state', 'rabbinate-as-fourth-branch', 'rabbinic-authority-led', 'anti-lgbt', 'anti-progressive', 'family-values', 'opposes-western-wall-compromise', 'education-system-focused', 'judicial-overhaul', 'opposes-hostage-deals', 'sovereignty-annexation', 'anti-two-state']::text[], ARRAY['judicial-restraint','conscription-by-incentive','not-economy-focused']::text[], 'record')
) AS v(name_he, bloc, economic, security, religiosity, sector, tags, families, family_evidence)
WHERE p.name_he = v.name_he;

-- Logo corrections. Unguarded, unlike the logo statements earlier in this file: each replaces a
-- value that was actively wrong, and a guarded statement could never reach an already-seeded
-- database. Rationale (including the misattribution these fix) is in docs/party-classifications.md.
-- NOTE: being unguarded, these DO overwrite an admin-edited logo for these rows.
-- (La Liga's own correction moved into the leagues seed_leagues table above, 2026-08-12 -- the new
-- table carries the CURRENT logo directly instead of a superseded URL plus this unguarded fix-up,
-- and this statement being unconditional would otherwise defeat that table's admin_edited honouring
-- for la-liga's logo_url specifically.)
UPDATE upcoming_parties SET logo_url = '/logos/beit-tzioni-miluimnikim.png'
    WHERE name_he = 'בית ציוני - המילואימניקים';
-- Scoped to upcoming_parties on purpose: previous_parties.'הציונות הדתית' is the current Knesset
-- faction and keeps its 2022 logo. See the tuple in the guarded block above for why this one is
-- self-hosted rather than a Wikimedia URL.
UPDATE upcoming_parties SET logo_url = '/logos/religious-zionism-2026.png'
    WHERE name_he = 'הציונות הדתית';

-- Strip Wikipedia's utm_* referral params from stored logo URLs. 26 of the seeded URLs were copied
-- out of he.wikipedia.org with "?utm_source=he.wikipedia.org&utm_campaign=index&utm_content=original"
-- attached; upload.wikimedia.org ignores the query string when serving the file, so the params did
-- nothing except send referral tracking to Wikimedia on every page load.
--
-- This has to be its own statement, and it has to be unguarded. The literals above are all guarded
-- by "logo_url IS NULL", so cleaning them at the source only ever reaches a FRESH database -- an
-- already-seeded one keeps the cruft forever. Unguarded is safe here in a way it would not be for a
-- whole URL: it only ever removes a meaningless suffix, so an admin-curated logo keeps pointing at
-- the same image. Idempotent -- the LIKE makes it a no-op once clean.
UPDATE leagues          SET logo_url = split_part(logo_url, '?utm_source=', 1) WHERE logo_url LIKE '%?utm_source=%';
UPDATE clubs            SET logo_url = split_part(logo_url, '?utm_source=', 1) WHERE logo_url LIKE '%?utm_source=%';
UPDATE previous_parties SET logo_url = split_part(logo_url, '?utm_source=', 1) WHERE logo_url LIKE '%?utm_source=%';
UPDATE upcoming_parties SET logo_url = split_part(logo_url, '?utm_source=', 1) WHERE logo_url LIKE '%?utm_source=%';

-- The Joint List is temporarily removed from upcoming_parties (admin decision, 2026-07-16) --
-- left commented rather than deleted so it's a one-line restore if/when it should come back.
-- INSERT INTO upcoming_parties (name, name_en, name_he) VALUES ('הרשימה המשותפת', 'The Joint List', 'הרשימה המשותפת') ON CONFLICT (name) DO NOTHING;