apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: {{ .Release.Namespace }}
