#!/usr/bin/env bash
# Usage: ./scripts/generate-inventory.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_DIR="$SCRIPT_DIR/../terraform"
INV_DIR="$SCRIPT_DIR/../ansible-project/inventories/voteball"

cd "$TF_DIR"

APP_IP=$(terraform output -raw app_public_ip)
RDS_ENDPOINT=$(terraform output -raw rds_endpoint | cut -d: -f1)
SNS_TOPIC=$(terraform output -raw sns_topic_arn)

mkdir -p "$INV_DIR/group_vars/all"

cat > "$INV_DIR/hosts" <<EOF
[app]
voteball-app ansible_host=${APP_IP}

[all:vars]
ansible_user=ec2-user
EOF

cat > "$INV_DIR/group_vars/all/main.yml" <<EOF
# Generated by scripts/generate-inventory.sh — do not edit by hand.
aws_region: il-central-1

db_host: ${RDS_ENDPOINT}
db_name: postgres
db_user: postgres

sns_topic: ${SNS_TOPIC}

frontend_domain: voteball.latnook.com
EOF

echo "Inventory written to $INV_DIR"
echo "Next: set db_pass and admin_secret in inventories/voteball/group_vars/all/secrets.yml"
