#!/usr/bin/env bash
# Renders argocd/voteball-application.yaml.tmpl to stdout, filling ${REPO_URL} from Terraform.
#
# WHY THIS EXISTS: the Application's repoURL used to be the literal https://github.com/Latnook/voteball,
# hardcoded in a file applied by `kubectl apply -f`. kubectl cannot interpolate Terraform variables --
# structurally the same problem that forces terraform/backend.hcl to be generated by
# bootstrap-tf-backend.sh -- so it was the one piece of this deployment's identity a forker had to find
# and edit by hand. Now it comes from the `github_repo` output like everything else.
#
#   ./scripts/render-argocd-app.sh | kubectl apply -f -    # what deploy.sh does
#   ./scripts/render-argocd-app.sh                         # inspect what would be applied
#
# Output goes to stdout and is never written to disk: a generated file in the working tree is a file
# someone eventually edits, and its edits are silently discarded on the next deploy.
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root

. scripts/lib/config.sh
TEMPLATE="argocd/voteball-application.yaml.tmpl"

# Same stub convention as scripts/sync-values-from-tf.sh: ARGOCD_STUB_<output> lets the test suite run
# with no AWS credentials and no applied stack.
tf_output() {
  local name="$1" stub
  stub="ARGOCD_STUB_${name}"
  if [ -n "${!stub:-}" ]; then
    printf '%s' "${!stub}"
    return 0
  fi
  if ! terraform -chdir="$TF_DIR" output -raw "$name" 2>/dev/null; then
    echo "ERROR: could not read Terraform output '${name}'." >&2
    echo "Is the stack applied? Try: terraform -chdir=${TF_DIR} output" >&2
    exit 1
  fi
}

[ -f "$TEMPLATE" ] || { echo "ERROR: $TEMPLATE not found." >&2; exit 1; }

GITHUB_REPO="$(tf_output github_repo)"

# Validate the SHAPE, not just non-emptiness. `github_repo` is documented as owner/name, but a full
# URL in voteball.tfvars is the natural mistake -- and it would compose into
# https://github.com/https://github.com/owner/name, which ArgoCD accepts as an Application and only
# then fails to fetch, reporting "repository not accessible" rather than "your tfvars is wrong".
case "$GITHUB_REPO" in
  */*/*|*:*|"")
    echo "ERROR: github_repo must be owner/name, got: '${GITHUB_REPO}'" >&2
    echo "       Fix github_repo in ${TFVARS} and re-apply." >&2
    exit 1
    ;;
  */*) ;;
  *)
    echo "ERROR: github_repo must be owner/name, got: '${GITHUB_REPO}'" >&2
    echo "       Fix github_repo in ${TFVARS} and re-apply." >&2
    exit 1
    ;;
esac

REPO_URL="https://github.com/${GITHUB_REPO}"

# `|` as the delimiter because the replacement is a URL full of slashes.
RENDERED="$(sed "s|\${REPO_URL}|${REPO_URL}|g" "$TEMPLATE")"

# Fail closed on any placeholder the template gained that this script does not know about. Without
# this, a new ${...} would reach kubectl verbatim: ArgoCD would accept the Application and then behave
# as though the field were misconfigured, which points at ArgoCD rather than at this script.
if printf '%s' "$RENDERED" | grep -q '\${'; then
  echo "ERROR: unsubstituted placeholder left in the rendered manifest:" >&2
  printf '%s' "$RENDERED" | grep -n '\${' >&2
  echo "       Teach scripts/render-argocd-app.sh about it before applying." >&2
  exit 1
fi

printf '%s\n' "$RENDERED"
