# Remote state for the Jenkins build-host stack.
#
# Same shape as terraform/backend.tf, and for the same reason: a `backend` block cannot interpolate
# variables, and the bucket name contains the AWS account id. Values come from backend.hcl,
# generated by scripts/bootstrap-tf-backend.sh:
#
#     terraform -chdir=terraform/jenkins init -backend-config=backend.hcl
#
# This stack shares the main stack's bucket but uses a SEPARATE key (voteball/jenkins.tfstate), so
# the two states -- and their locks -- stay independent. That independence is the whole point: the
# main stack is destroyed and rebuilt routinely while this host keeps running.
#
# See docs/design/2026-07-21-terraform-remote-state-design.md.
terraform {
  backend "s3" {
    use_lockfile = true
    encrypt      = true
  }
}
